[package]
name = "stresser"
version = "0.0.1"
authors = ["Sergey"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }